version: '3.5'
include:
    - ../auth/docker-compose.local.yaml
    - ../tickets/docker-compose.local.yaml
    - ../events/docker-compose.local.yaml
    - ../attendance/docker-compose.local.yaml
services:
    gateway:
        image: nginx:1.19-alpine
        restart: unless-stopped
        volumes:
            - ./docker/gateway/conf.d:/etc/nginx/conf.d:ro
            - ./gateway:/var/www/app
            - ./.ssl:/etc/ssl/certs
        depends_on:
            - auth_nginx
            - tickets_nginx
            - events_nginx
            - attendance_nginx

    database:
        image: postgres:12.20-alpine
        restart: unless-stopped
        volumes:
            - database:/var/lib/postgresql/data:delegated
        environment:
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_USER: '${DB_USER}'
            POSTGRES_DB: '${DB_NAME}'
    rabbitmq:
        image: rabbitmq:3-management-alpine
        restart: unless-stopped
        hostname: rabbitmq
        
        volumes:
            - rabbitmq:/var/lib/rabbitmq/
            - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            - ./docker/rabbitmq/definition.json:/etc/rabbitmq/definition.json
        environment:
            RABBITMQ_DEFAULT_USER: '${RABBITMQ_USER}'
            RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASSWORD}'
            CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 30s
            retries: 3
volumes:
    database:
    rabbitmq: